export type {
  AccountImpactResult,
  CategoryAnalytics,
  CreateCategoryDTO,
  CreateMovementDTO,
  CreateRuleDTO,
  CreateSpaceDTO,
  InviteMemberDTO,
  MemberAnalytics,
  PaginatedResponse,
  SharedCategory,
  SharedInvitation,
  SharedMovement,
  SharedMovementDetail,
  SharedNotification,
  SharedSpace,
  SharedSpaceMember,
  SharedSpacesSummary,
  SharedSplitRule,
  SpaceAnalyticsSummary,
  SpaceBalance,
  TrendPoint,
  UpdateSpaceDTO,
} from '../../../types/sharedSpaces';

